backend:
    ALLEGRO_SECRET: ENC[AES256_GCM,data:XCEG8xZVaC9x2Cu6EEwziCH1P3qiigW5wKtBteRL6hxR8oEd23A7VdBsIcW3M0IXEvTZ72A4RlhPOleu+IYUVQ==,iv:LF/omksqyQ2E30KuM7R8yqBNDDVekzkAiWDav+Y7hQY=,tag:ipFMpywGYNaIoGWVvUGIxQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:5MdCgYHdN1Y6wzY6Ybtnu7VBGguSidAH+0tgKbfSpr4sB9NTIBPEab9kLUhJSI6HqySdf7HRyMeDze0he1OLuQ==,iv:OnRf1KLv/1F1+Ab8HB7UxWauCGO9QcFkB3bkUOInCVY=,tag:INEE1aCHezkO1hGnSTTZlQ==,type:str]
    FACEBOOK_SECRET: ENC[AES256_GCM,data:pzqIXFJfSOPWZpvV+feNu/Jk+itu6ji0NKw8RNEOkQA=,iv:DlxTzgvJdtXIcijAfB0vcxd7KHW1vi7goU2oWbfIaBA=,tag:rBc91+pyurrxlk2A9Mo9vw==,type:str]
    GITHUB_SECRET: ENC[AES256_GCM,data:hhMnkQOUKNYC8WS7Blwx0xPtFXJC+V53LnFHSdiku8CBv+GAjV83EQ==,iv:Q/Vy5twSXN3q5gSQex0+/9FzaQGhEGHjh5NmyZy27ro=,tag:tQkYSdua29iXBS2fgeHTpw==,type:str]
    GOOGLE_SECRET: ENC[AES256_GCM,data:y00uh7uYxXlxmynNnxT76cAa8PeVTfRc,iv:q0LidI6nqQrNEzYbPLKJ/8dcusyI2Hqi6wD62KSwIiI=,tag:xW0hp7+LP6Hr8qcsJDf8qg==,type:str]
    JWT_KEY: ENC[AES256_GCM,data:IKOYO6yEE2u4LXL5hO9cq1DBnYvY/uq9ZKg5nn1gJA8w,iv:l/vH1WCVsNz+SI+3rFcxhroSVxbjwz1hj1EsaWjDAkg=,tag:SbQrzyxrqJK/BvjRhSnlgw==,type:str]
    MAIL_KEY: ENC[AES256_GCM,data:WobCQndFDIxzwnqvW4klgTIfBZ2zKQ==,iv:T+klP4xjFuFzrz3SkZ8QcgBdEufIeGkMcQpMZMeef4o=,tag:3lPKTkiJRYwWQY3GogkOHQ==,type:str]
    TWITTER_ACCESS_TOKEN: ENC[AES256_GCM,data:/RhU48sndKWmt1w1qD1RHbO4oqYjj73djPC8qVh5Ur/Rzf2NdBi1RZetgPn6DZxafJk=,iv:sOCvZF0sby08HfI/7LYj/Vw+AEOkawL4v4Z3VFl9d8M=,tag:wjp71QE16gSw65f5vuBW3w==,type:str]
    TWITTER_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:nnHFEfl1SXjKjFfEVN99slR9Zj1Vz5H6gbEm5C9cQ4MTh8hbp/ElftBZmzEY,iv:V03x6JudGOas/EY78g+uwGEkJX0CSlcPra77Nz92f14=,tag:TXJNvhigYjA7tmjhUafrgA==,type:str]
    TWITTER_SECRET: ENC[AES256_GCM,data:Qm134Vl3ATVJ0Go0D5MbrDHdnQTQR/4oezZinhqAuZpKIo4Buxl7c3gW7j8eCO4PXrQ=,iv:fyATUiXVy+g5UB1d3wNBtSd5Afb6e5tUOmS5LOIumtk=,tag:W+RKnLLoD1+JGJL8KJKN2w==,type:str]
    CHAT_DATALINKS_TOKEN: ENC[AES256_GCM,data:FDATw3VHmZQ5g8Wru/hAHf6g+z8aqCw+InAE+0JNJVDiyAQYf12NTZvvts25MyHRwXMeNaHxqU2NQRT9yBgmCs46AYlTpu7jD05cy3EMAKPZCfSFF14Ui5KZSwZ0h2niQWKiBMg95JPb8QBhbre0AbuoprbB6xxQiztDvPnjE8ljoXbkW92KIha/6sbyA7/rAahAVNasYxNfsPq/HEfw6+7jiOVhi+fwN+TsDrL+Hs3imP8jWiKif+ac+wDcTJUL27HOFKN26YOI9ZxcXP1DWVibhgLfIafwdu8gdds7SKh3,iv:Mi0F2svPWrYYqzaPyqvqtebzc+UEFph3LFF37EhEAOI=,tag:YJP3EBcLcPVkU7sZaW4l5g==,type:str]
    CHAT_SECRET: ENC[AES256_GCM,data:c8JumRTDAAHoqOwKhlm76cSuRZhhnbokwKAliFjhWNA=,iv:mvhB7vLupW8f1zL9Bf9/lgkL/5YSjELQLr7HyfyFmrA=,tag:dPImGMoWqeVv970rZ+8u5g==,type:str]
webpage:
    NUXT_PUBLIC_GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:Gh1mdqBZQ4xdVlFr8CZSLZJ66YMn9d/iV1Mo/NarcLxVbH6U4H+V,iv:GVvLrCWEWS87i56O5v4ugDXuHE5OfIniTB+HK59clrE=,tag:QxkR0BU3+VJyVfx3uhVLPg==,type:str]
    NUXT_PUBLIC_CHAT_SECRET: ENC[AES256_GCM,data:LXmqgf8a15cWy+dH4J+bnkdOLGWAZbmWECFVP3hyQ30=,iv:bb5LnldVayy0aofarnZMymsM3CZsyOZnyE4lQe12TM8=,tag:TcAVQjRn7yCFjRLuJ23obw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDemlqSXM5UkhvSzI1WC9C
            UE1LTWxMNE5ZVWgxNmRUMTd1QURVZnF5NFRvCjRiMm4ydVZDazB3cTMzaVJYNlI5
            cmFabExjd2hDTHpDdEhNNk9pQmxneTgKLS0tIDNVYTFiMXVrL1pGbXJKclRpZ0Fn
            WEZjS1JhcjFQWDk5eHFvcU1HVXE4QU0KaXDFhNnzIFAnEDYDq2/9B69Z6o2FSGjI
            zHsS2Nqsr1wQrtIcetPMUW+VFOHK+cIjCYBVyBmS/TSTDes1aY27rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ng3cmz76z97epjj26zyx202puzsv2ljqhyfw0629j5yctj9nrv5st6p9wg
    lastmodified: "2026-10-09T22:25:28Z"
    mac: ENC[AES256_GCM,data:M9tC2jk0kYc12QEM+4MFn1TV4gISWMsUm9e0s69hl2ckEYqo61k3e86Gz+UAn4JuSsmuAydR4SAf+l3CZrKU/W0rdPbMMvjvgeAz3fOaucU7aUraa2BDGuzWFprbsuCdB3P1lculOAC2cz5Ido7lNU1iwA/wo8hNA80WCbffzt0=,iv:g+O+OYXzSvgn03sDnwNNj7cfRjkayd1G1bhev5JMZVI=,tag:LwgDujOxRwB+eb4bwsrZQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
