#ENC[AES256_GCM,data:BtmRotOlOxYTft8zQAgAyAP2wyyWlA0RRiViPb2CAiCOa4SnmkSmPh7WgtFngn3PYpf2YzRAiw==,iv:tQVqjUq4PR+0Wpy1VMZGvk1G8+gzLPjmI5xFfob09gg=,tag:epNx/pi48zfo3fy0iYdZ9g==,type:comment]
#
#ENC[AES256_GCM,data:s3zgnO/iGtujX7bOtyZBxXXuhIOnF4k7GhcEN/pexwrfHpp3K5HMOJGd2jEXydkK,iv:zColQvjgMYf9TFad70S/b2XIpkfLfTrp3TeA+rLH8n4=,tag:ow5FOclzBg6DE5dEkj4EHg==,type:comment]
#ENC[AES256_GCM,data:gUjsjhmBfCwV+vuGaxwRl0TSBqsc3Q01tXhrXb7cMOO+QaAp6SS3J3bVZE3nuM+aYoKYb/vHUD0T5vi+aLekKw==,iv:5YseJ5/qAnk9eJgGcYT+vAhB1SO+IKVT9FJd+1i/OxY=,tag:wI8nMC2kmfKTFUcDxosPPw==,type:comment]
#
#ENC[AES256_GCM,data:JMdF4685JFlg3V4V4boJNXC6ZMpP/aUtACuDRGp9QfQJabs7qhZHVqbq+830HLqY1ctw,iv:33Nl9eky15JbfcLINq3ZM7yS8hF+kVz9P2SdlR2PxuE=,tag:MmSP9oSxQfErGxD3p5+SNA==,type:comment]
#ENC[AES256_GCM,data:E5HMXA2KGnnQ8oZMh0joeiZJymFMAUy5a/5nezSV7ecdFXsZUO7QeWQ=,iv:AMUtz0dQWZo2nHDI8tFgyV42O98bEaKUe1ZcTAfD1u4=,tag:GNN3quk0Xs/HXz443Kpgtg==,type:comment]
_placeholder:
    NOTE: ENC[AES256_GCM,data:8NdbvPlMdUGHVjl6ksgXuUYfSNXI10dg22iPYTAiQ87Mpg7WFhCu4AhLogVGokzfEx4Xr3mdlwy0VQ/BAjfj+54Qewhe7h5bo8qY6DyN9A59KEDOJwTt,iv:UQfl4SFUVvcIWzvRZSp+9VJAjqCj8MKKs+AMDAXAv+U=,tag:OlKESy+F5LYJQgwEFezGQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL09HSmNqMU8yVmRpemhu
            T0NtUG9rdmdtVFZTdmhoc3J6NW5ER3c5VVJNCml2cDU3R2lVZElZRFBxenprUU15
            WUd3RlBJUGJoKzM2ekNJZVNlRVNtZlkKLS0tIGcrT3VCQzBCL09MTHZRUG94VUh6
            cjJ5WUFDOHBybUE4TWU0cldlOFZJZDAKGtKtUMUKFWTumIcFJDab28fvn0QBDaB5
            p28HqhTVWev0ZWLs6K4VFjJlQmuy2LGTHKnD6tSK4Qu/VSI1ckwVXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13eqrswezlp5932t5dv494n6t6wj3rsa4vf5kjt7mcewhp0xuzs8sj26qfx
    lastmodified: "2026-10-05T19:50:14Z"
    mac: ENC[AES256_GCM,data:JLB/GCcTprBrNF7WFNm0HXjUQwqgc9Hzv+dDl1usZC73fX2STt5hBuNAdzhaHh954H7JEC1tNehaHi6z1diXO+0KQ4eFOfPn1aKDMjV3/LDFf5mgB+zOmYhtUej0LcPHQHUFdMH12D0wvzVHm/zf5sSYvcFn60yqviaIPuw/42c=,iv:Ot1rJhi3WtHMGrg2pGgrKZE7dvRKwb1tnNIj1IkiT6Q=,tag:l/DNIeePtRaaSt7Cw+dAgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
