#ENC[AES256_GCM,data:H1pkFcVMWFXic+psZlGO+66gpsT9qQX722kd1SR8YwB3mKfYyXcm3UgSHKuYk9iKqmdqIjtTFnZ3wB263A==,iv:b9YqeYg0rLX3fPb9BBlsyl7s86rSr7gsS7F1VuZh6EY=,tag:8POB2NBppoDJ5oPhRF3jHA==,type:comment]
#ENC[AES256_GCM,data:UL0nIJMkv5kWCbEjt3ZNrZ/mBKVZGqPAgOtyoA5EuehD7oPOktq+2fL35gSPhdD/rabmNkxtgReZ4knbut1cHDezF+bJ6hQSxWi4oNudQCSCKtHDGlg7KCOEGYoihEadB+4=,iv:aRjEijNV596vXW+Ga4uGs46WP2ym3kjU23fIiUzIZ+M=,tag:0Y5RmxBKJUFVAHdJCqT9ew==,type:comment]
_placeholder:
    NOTE: ENC[AES256_GCM,data:zcOHyaCAlPwn4vbQe90=,iv:hJHnLtUwNaCe6og3JYkBNd/n156H3dZAhh03inw0cRE=,tag:GNMI6l13rMkJFXDZ3zXF9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXek5DMkF5aW9tRVk5NWJO
            bDBvTVgvelozQzY3K2phRlFTcHhYZ1NJdnlZClZJZVpNbklNTXNCa3Y3MFE3c2tB
            djA4b0dTemhialJPNm1oSXBIRnlYc0kKLS0tIDRqNnRLUFZRR2tXb0JmZytQOTZQ
            ZUVqS1lSd0NqK2IzQVJMTlVnWG5BOWMKkbOt8QlbR0KmzMU6eiFlubix1xmkYL+M
            B8cmra5kXhybIt2ZtUZV0ZAn0X46WAhvgX7KJ8yxRbE+Z9WDQ+GcEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ng3cmz76z97epjj26zyx202puzsv2ljqhyfw0629j5yctj9nrv5st6p9wg
    lastmodified: "2026-10-09T22:11:09Z"
    mac: ENC[AES256_GCM,data:38FyBwkoBWIod+wge6pA9BGklYQQfOTI4puhWWIJoPtj8j6wonlF4e69rDKuUR/Ojw7TmrGRGpMt1MBvtTIF3KRlJNv4iVrQya4/LWa3TiSSeNgIxCgGTYrAy8+QVE1N4gpdNtx6vtczmPC62ewAUN/UKXr+zY9lmr0BUvVXXJU=,iv:kT3mMTst1qtkUNFGmXPKGLCg72iBT4JK5fcy7cFQHBI=,tag:zFNfT+aeki4g39ip8yFv+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
