/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/agenda'
      | '/admin/pages'
      | '/admin/presentation-preview.[[id]]'
      | '/admin/presentations'
      | '/admin/rates'
      | '/admin/users'
    >,
    '/admin/agenda': RouteRecordInfo<
      '/admin/agenda',
      '/admin/agenda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/pages': RouteRecordInfo<
      '/admin/pages',
      '/admin/pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/presentation-preview.[[id]]': RouteRecordInfo<
      '/admin/presentation-preview.[[id]]',
      '/admin/presentation-preview/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/admin/presentations': RouteRecordInfo<
      '/admin/presentations',
      '/admin/presentations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/rates': RouteRecordInfo<
      '/admin/rates',
      '/admin/rates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/homepage.[[id]]': RouteRecordInfo<
      '/homepage.[[id]]',
      '/homepage/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login.[provider]': RouteRecordInfo<
      '/login.[provider]',
      '/login/:provider',
      { provider: ParamValue<true> },
      { provider: ParamValue<false> },
      | never
    >,
    '/presentation-form.[[id]].[[userId]]': RouteRecordInfo<
      '/presentation-form.[[id]].[[userId]]',
      '/presentation-form/:id?/:userId?',
      { id?: ParamValueZeroOrOne<true>, userId?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false>, userId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/privacy-policy': RouteRecordInfo<
      '/privacy-policy',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile-form.[[id]]': RouteRecordInfo<
      '/profile-form.[[id]]',
      '/profile-form/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/rate.[[entryId]]': RouteRecordInfo<
      '/rate.[[entryId]]',
      '/rate/:entryId?',
      { entryId?: ParamValueZeroOrOne<true> },
      { entryId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/vote-for-papers': RouteRecordInfo<
      '/vote-for-papers',
      '/vote-for-papers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workshop-form.[[id]].[[userId]]': RouteRecordInfo<
      '/workshop-form.[[id]].[[userId]]',
      '/workshop-form/:id?/:userId?',
      { id?: ParamValueZeroOrOne<true>, userId?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false>, userId?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/agenda'
        | '/admin/pages'
        | '/admin/presentation-preview.[[id]]'
        | '/admin/presentations'
        | '/admin/rates'
        | '/admin/users'
      views:
        | 'default'
    }
    'src/pages/admin/agenda.vue': {
      routes:
        | '/admin/agenda'
      views:
        | never
    }
    'src/pages/admin/pages.vue': {
      routes:
        | '/admin/pages'
      views:
        | never
    }
    'src/pages/admin/presentation-preview.[[id]].vue': {
      routes:
        | '/admin/presentation-preview.[[id]]'
      views:
        | never
    }
    'src/pages/admin/presentations.vue': {
      routes:
        | '/admin/presentations'
      views:
        | never
    }
    'src/pages/admin/rates.vue': {
      routes:
        | '/admin/rates'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/homepage.[[id]].vue': {
      routes:
        | '/homepage.[[id]]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/login.[provider].vue': {
      routes:
        | '/login.[provider]'
      views:
        | never
    }
    'src/pages/presentation-form.[[id]].[[userId]].vue': {
      routes:
        | '/presentation-form.[[id]].[[userId]]'
      views:
        | never
    }
    'src/pages/privacy-policy.vue': {
      routes:
        | '/privacy-policy'
      views:
        | never
    }
    'src/pages/profile-form.[[id]].vue': {
      routes:
        | '/profile-form.[[id]]'
      views:
        | never
    }
    'src/pages/rate.[[entryId]].vue': {
      routes:
        | '/rate.[[entryId]]'
      views:
        | never
    }
    'src/pages/vote-for-papers.vue': {
      routes:
        | '/vote-for-papers'
      views:
        | never
    }
    'src/pages/workshop-form.[[id]].[[userId]].vue': {
      routes:
        | '/workshop-form.[[id]].[[userId]]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
