[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["npm install -g pnpm@10.5.2"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx serve dist"
