[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.5.2 --activate",
  "pnpm install --frozen-lockfile",
  "pnpm add serve",
]

[phases.build]
cmds = ["pnpm run build"]

[variables]
VITE_API_URL = "https://api.confitura.pl/api"
VITE_SELF_URL = "https://app.confitura.pl"

[start]
cmd = "./node_modules/.bin/serve -s dist"
