[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NUXT_PUBLIC_API_SERVER = "https://api.confitura.pl/api/resources/archive/2025/"
NUXT_PUBLIC_FILE_SERVER = "https://api.confitura.pl"
