[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.5.2 --activate",
  "pnpm install --frozen-lockfile",
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NUXT_PUBLIC_API_SERVER = "https://api.confitura.pl/api/resources/archive/2026/"
NUXT_PUBLIC_FILE_SERVER = "https://api.confitura.pl"
