[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g pnpm@10.12.4"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NUXT_PUBLIC_API_SERVER = "https://api.confitura.pl/api/resources/archive/2025/"
NUXT_PUBLIC_FILE_SERVER = "https://api.confitura.pl"
