jobs:
  include:
    - language: java
      script: mvn package
      before_script: cd jelatyna-backend
    - language: node_js
      node_js:
        - "10"
      script: yarn build:full
      before_script: cd confitura-vue
    - language: node_js
      node_js:
        - "8"
      script: yarn build:full
      before_script: cd confitura-page
