version: "3.3"
services:

#  frontend:
#    build: confitura-vue
#    volumes:
#      - ./confitura-vue/src:/opt/app/src

  backend:
    build: jelatyna-backend
    volumes:
      - ./jelatyna-backend/src:/opt/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/confitura?useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: confitura
      SPRING_DATASOURCE_PASSWORD: password
      JWT_KEY: /tmp
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      MAIL_API_KEY: 123
      RESOURCES_PATH: /tmp
      RESOURCES_FOLDER: /tmp
    links:
      - mysql

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/data:/www/data
    links:
#      - frontend
      - backend

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'confitura'
      MYSQL_USER: 'confitura'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
