[phases.setup]
nixPkgs = ["jdk21", "bash", "coreutils"]
aptPkgs = ["bash"]
cmds = ["ln -sf $(which bash) /bin/bash 2>/dev/null || true", "ln -sf $(which sh) /bin/sh 2>/dev/null || true"]

[phases.install]
cmds = ["./mvnw dependency:go-offline -q"]

[phases.build]
cmds = ["./mvnw package -DskipTests -q"]

[start]
cmd = "java -jar target/jelatyna-0.0.1-SNAPSHOT.jar"
