server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jelatyna
    username: jelatyna
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
resources.path: /tmp
resources.folder: /tmp
jwt.key: /tmp
mail.apiKey: 123

app:
  cors:
    origins:
      - http://localhost:5173/
