server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:jelatyna
    username: confitura
    password: confitura

resources.path: /tmp
resources.folder: /tmp
jwt.key: /tmp
mail.apiKey: 123

app:
  cors:
    origins:
      - http://localhost:5173/
