// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost' | (string & {});
};

export type AllegroContext = {
    auctionId?: string;
    auctionName?: string;
    buyerLogin?: string;
};

export type AskRequest = {
    conversationId?: string;
    question?: string;
};

export type AssignAgendaEntryRequest = {
    dayId: string;
    label: string;
    presentationId: string;
    roomId?: string;
    timeSlotIndex: number;
};

export type CreateRoomRequest = {
    displayOrder?: number;
    label: string;
};

export type CreateTimeSlotRequest = {
    /**
     * End time, e.g. 10:00
     */
    end: string;
    forAllRooms?: boolean;
    /**
     * Start time, e.g. 09:00
     */
    start: string;
};

export type Day = {
    createdBy?: string;
    createdDate?: string;
    date: string;
    displayOrder: number;
    id?: string;
    label: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
};

export type DumpResponse = {
    triggeredAt?: string;
};

export type DumpStatus = {
    lastDumpAt?: string;
};

export type FaqEntryDto = {
    answer?: string;
    category?: string;
    displayOrder?: number;
    id?: string;
    published?: boolean;
    question?: string;
};

export type FaqEntryRequest = {
    answer?: string;
    category?: string;
    displayOrder?: number;
    published?: boolean;
    question?: string;
};

export type FullPresentation = {
    description: string;
    durationInMinutes: number;
    expectedPrice: number;
    flatSpeakers: string;
    flatTags: string;
    id: string;
    isFree: boolean;
    isWorkshop: boolean;
    language: string;
    level: string;
    maxGroupSize: number;
    shortDescription: string;
    speakers: Array<Speaker>;
    status: string;
    tags: Array<string>;
    title: string;
};

export type FullUser = {
    bio?: string;
    email?: string;
    github?: string;
    hasAcceptedPresentation?: boolean;
    id?: string;
    isAdmin?: boolean;
    isParticipant?: boolean;
    isSpeaker?: boolean;
    isVolunteer?: boolean;
    name?: string;
    origin?: string;
    photo?: string;
    privacyPolicyAccepted?: boolean;
    twitter?: string;
    username?: string;
    www?: string;
};

export type GenerateVouchersRequest = {
    comment?: string;
    email?: string;
    participantVouchers?: number;
    sponsorVouchers?: number;
};

export type InlineAgendaEntry = {
    dayId: string;
    id: string;
    label?: string;
    presentationId?: string;
    roomId?: string;
    roomLabel?: string;
    timeSlotIndex: number;
    timeSlotLabel?: string;
    timeSlotSpan?: number;
};

export type InlineDay = {
    date: string;
    displayOrder: number;
    id: string;
    label: string;
};

export type InlinePresentation = {
    description: string;
    id: string;
    language: string;
    level: string;
    shortDescription: string;
    status: string;
    tags: Array<string>;
    title: string;
};

export type InlinePresentationWithSpeakers = {
    description?: string;
    durationInMinutes?: number;
    expectedPrice?: number;
    id?: string;
    isFree?: boolean;
    language?: string;
    level?: string;
    maxGroupSize?: number;
    shortDescription?: string;
    sortableTitle?: string;
    speakers?: Array<Speaker>;
    tags?: Array<Tag>;
    title?: string;
    workshop?: boolean;
};

export type InlineRoom = {
    displayOrder: number;
    id: string;
    label: string;
};

export type InlineTimeSlot = {
    /**
     * Day identifier
     */
    dayId: string;
    displayOrder: number;
    end: string;
    forAllRooms: boolean;
    label: string;
    start: string;
};

export type InlineVote = {
    id: string;
    order: number;
    presentation: InlineVotePresentation;
    rate: number;
};

export type InlineVotePresentation = {
    id: string;
    longDescription: string;
    shortDescription: string;
    speakers: Array<InlineVoteSpeaker>;
    title: string;
    workshop: boolean;
};

export type InlineVoteSpeaker = {
    bio: string;
    id: string;
    name: string;
    photo: string;
};

export type InlineWorkshop = {
    description: string;
    durationInMinutes: number;
    expectedPrice: number;
    id: string;
    isFree: boolean;
    language: string;
    level: string;
    maxGroupSize: number;
    shortDescription: string;
    status: string;
    tags: Array<string>;
    title: string;
};

export type Like = {
    id?: string;
    presentation?: Presentation;
    token: string;
};

export type LikeResponse = {
    id?: string;
    presentationId?: string;
};

export type MessageInfo = {
    email?: string;
    ticket?: string;
    variables?: {
        [key: string]: string;
    };
};

export type NewsletterStat = {
    subscribersCount?: number;
};

export type PageContent = {
    content?: string;
};

export type ParticipationData = {
    arrivalDate?: string;
    createdBy?: string;
    createdDate?: string;
    email?: string;
    firstName?: string;
    fullName?: string;
    gender?: string;
    id?: string;
    info?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    lastName?: string;
    privacyPolicyAccepted?: boolean;
    registeredBy?: string;
    registrationDate?: string;
    size?: string;
    surveySendDate?: string;
    ticketSendDate?: string;
    voucher?: Voucher;
};

export type PartnerDto = {
    description?: string;
    id?: string;
    logo?: string;
    name?: string;
    orientation?: string;
    published?: boolean;
    slug?: string;
    type?: string;
    www?: string;
};

export type PartnerRequest = {
    description?: string;
    name?: string;
    orientation?: string;
    published?: boolean;
    slug?: string;
    type?: string;
    www?: string;
};

export type PreSelectionRequest = {
    comment?: string;
    status?: 'NONE' | 'PRE_APPROVED' | 'PRE_REJECTED' | 'IN_RESERVE';
};

export type Presentation = {
    accepted?: boolean;
    description: string;
    durationInMinutes?: number;
    expectedPrice?: number;
    id?: string;
    isFree?: boolean;
    language: string;
    level: string;
    maxGroupSize?: number;
    new?: boolean;
    preSelectionComment?: string;
    preSelectionStatus?: 'NONE' | 'PRE_APPROVED' | 'PRE_REJECTED' | 'IN_RESERVE';
    ratings?: Array<Rate>;
    shortDescription: string;
    speakers: Array<User>;
    status?: string;
    tags?: Array<Tag>;
    title: string;
    workshop?: boolean;
};

export type PresentationRequest = {
    description?: string;
    language?: string;
    level?: string;
    shortDescription?: string;
    tags?: Array<string>;
    title?: string;
};

export type PresentationStats = {
    negativeVotes?: number;
    positiveVotes?: number;
    presentationId?: string;
    rateOfNegative?: number;
    rateOfPositive?: number;
    title?: string;
    totalVotes?: number;
};

export type PublicSpeaker = {
    bio?: string;
    github?: string;
    id?: string;
    name?: string;
    photo?: string;
    presentations?: Array<Presentation>;
    twitter?: string;
    www?: string;
};

export type Rate = {
    comment?: string;
    id?: string;
    presentation?: Presentation;
    reviewerToken?: string;
    value?: 'AWESOME' | 'GREAT' | 'IT_WAS_FINE' | 'BAD' | 'TERRIBLE';
};

export type RateRequest = {
    comment?: string;
    id?: string;
    reviewerToken?: string;
    value?: number;
};

export type RegistrationError = {
    additionalInfo?: string;
    reason?: string;
};

export type RenameCategoryRequest = {
    from?: string;
    to?: string;
};

export type ReorderRequest = {
    ids?: Array<string>;
};

export type Room = {
    createdBy?: string;
    createdDate?: string;
    day: Day;
    displayOrder: number;
    id?: string;
    label?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
};

export type SendMailsRequest = {
    messageInfoList?: Array<MessageInfo>;
    template?: string;
};

export type Speaker = {
    id?: string;
    name?: string;
};

export type SseEmitter = {
    timeout?: number;
};

export type SubmittedStats = {
    presentations?: number;
    total?: number;
    workshops?: number;
};

export type Tag = {
    id?: string;
    name?: string;
};

export type Tweet = {
    avatar?: string;
    name?: string;
    text?: string;
    time?: string;
    twitterHandle?: string;
};

export type UpdateAgendaEntryRequest = {
    label?: string;
    presentationId?: string;
    roomId?: string;
};

export type UpdateAgendaEntrySlotRequest = {
    dayId: string;
    roomId?: string;
    timeSlotIndex: number;
};

export type UpdateDayRequest = {
    /**
     * Date of the day, e.g. 2026-09-19
     */
    date: string;
    displayOrder: number;
    label: string;
};

export type UpdateRoomRequest = {
    displayOrder?: number;
    label?: string;
};

export type UpdateTimeSlotRequest = {
    /**
     * End time, e.g. 10:00
     */
    end?: string;
    forAllRooms?: boolean;
    /**
     * Start time, e.g. 09:00
     */
    start?: string;
};

export type User = {
    admin?: boolean;
    bio?: string;
    createdBy?: string;
    createdDate?: string;
    email?: string;
    github?: string;
    id?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    name?: string;
    origin?: string;
    participant?: boolean;
    participationData?: ParticipationData;
    photo?: string;
    privacyPolicyAccepted?: boolean;
    socialId?: string;
    speaker?: boolean;
    twitter?: string;
    username?: string;
    volunteer?: boolean;
    www?: string;
};

export type UsersStats = {
    admins?: number;
    total?: number;
    volunteers?: number;
};

export type ViewPresentationRate = {
    avgRating?: number;
    presentationId?: string;
    ratingCount?: number;
    ratingCountAwesome?: number;
    ratingCountBad?: number;
    ratingCountGreat?: number;
    ratingCountItWasFine?: number;
    ratingCountTerrible?: number;
    ratings?: Array<Rate>;
    speakers?: Array<Speaker>;
    title?: string;
};

export type VoteRequest = {
    id?: string;
    rate?: number;
};

export type VoteResult = {
    accepted: boolean;
    flatSpeakers: string;
    flatTags: string;
    negative: number;
    negativePercent: number;
    neutral: number;
    neutralPercent: number;
    positive: number;
    positivePercent: number;
    preSelectionComment: string;
    preSelectionStatus: 'NONE' | 'PRE_APPROVED' | 'PRE_REJECTED' | 'IN_RESERVE';
    presentationId: string;
    score: number;
    speakerHasPreSelectedPresentation: boolean;
    speakers: Array<Speaker>;
    title: string;
    total: number;
    voterScores: {
        [key: string]: number;
    };
    workshop: boolean;
};

export type Voucher = {
    allegro?: AllegroContext;
    comment?: string;
    createdBy?: string;
    createdDate?: string;
    emailSent?: boolean;
    id?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    originalBuyer?: string;
    ticketSendDate?: string;
    type?: 'PARTICIPANT' | 'SPEAKER' | 'SPONSOR';
};

export type WorkshopRequest = {
    description?: string;
    durationInMinutes?: number;
    expectedPrice?: number;
    isFree?: boolean;
    language?: string;
    level?: string;
    maxGroupSize?: number;
    shortDescription?: string;
    tags?: Array<string>;
    title?: string;
};

export type LikeWritable = {
    id?: string;
    presentation?: PresentationWritable;
    token: string;
};

export type MessageInfoWritable = {
    email?: string;
    name?: MessageInfoWritable;
    ticket?: string;
    token?: MessageInfoWritable;
    variables?: {
        [key: string]: string;
    };
};

export type PresentationWritable = {
    accepted?: boolean;
    description: string;
    durationInMinutes?: number;
    expectedPrice?: number;
    id?: string;
    isFree?: boolean;
    language: string;
    level: string;
    maxGroupSize?: number;
    new?: boolean;
    preSelectionComment?: string;
    preSelectionStatus?: 'NONE' | 'PRE_APPROVED' | 'PRE_REJECTED' | 'IN_RESERVE';
    ratings?: Array<RateWritable>;
    shortDescription: string;
    speaker?: PresentationWritable;
    speakers: Array<User>;
    status?: string;
    tags?: Array<Tag>;
    title: string;
    workshop?: boolean;
};

export type PublicSpeakerWritable = {
    bio?: string;
    github?: string;
    id?: string;
    name?: string;
    photo?: string;
    presentations?: Array<PresentationWritable>;
    twitter?: string;
    www?: string;
};

export type RateWritable = {
    comment?: string;
    id?: string;
    presentation?: PresentationWritable;
    reviewerToken?: string;
    value?: 'AWESOME' | 'GREAT' | 'IT_WAS_FINE' | 'BAD' | 'TERRIBLE';
};

export type SendMailsRequestWritable = {
    messageInfoList?: Array<MessageInfoWritable>;
    template?: string;
};

export type ViewPresentationRateWritable = {
    avgRating?: number;
    presentationId?: string;
    ratingCount?: number;
    ratingCountAwesome?: number;
    ratingCountBad?: number;
    ratingCountGreat?: number;
    ratingCountItWasFine?: number;
    ratingCountTerrible?: number;
    ratings?: Array<RateWritable>;
    speakers?: Array<Speaker>;
    title?: string;
};

export type TriggerWebpageDumpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin-tasks/webpage/dump';
};

export type TriggerWebpageDumpResponses = {
    /**
     * OK
     */
    200: DumpResponse;
};

export type TriggerWebpageDumpResponse = TriggerWebpageDumpResponses[keyof TriggerWebpageDumpResponses];

export type GetLastWebpageDumpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin-tasks/webpage/last-dump';
};

export type GetLastWebpageDumpResponses = {
    /**
     * OK
     */
    200: DumpStatus;
};

export type GetLastWebpageDumpResponse = GetLastWebpageDumpResponses[keyof GetLastWebpageDumpResponses];

export type GetAllDays1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agenda/days';
};

export type GetAllDays1Responses = {
    /**
     * OK
     */
    200: Array<InlineDay>;
};

export type GetAllDays1Response = GetAllDays1Responses[keyof GetAllDays1Responses];

export type SaveAgendaEntryData = {
    body: AssignAgendaEntryRequest;
    path?: never;
    query?: never;
    url: '/agenda/entries';
};

export type SaveAgendaEntryResponses = {
    /**
     * OK
     */
    200: InlineAgendaEntry;
};

export type SaveAgendaEntryResponse = SaveAgendaEntryResponses[keyof SaveAgendaEntryResponses];

export type DeleteAgendaEntryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/entries/{id}';
};

export type DeleteAgendaEntryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAgendaEntryByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/entries/{id}';
};

export type GetAgendaEntryByIdResponses = {
    /**
     * OK
     */
    200: InlineAgendaEntry;
};

export type GetAgendaEntryByIdResponse = GetAgendaEntryByIdResponses[keyof GetAgendaEntryByIdResponses];

export type UpdateAgendaEntryData = {
    body: UpdateAgendaEntryRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/entries/{id}';
};

export type UpdateAgendaEntryResponses = {
    /**
     * OK
     */
    200: InlineAgendaEntry;
};

export type UpdateAgendaEntryResponse = UpdateAgendaEntryResponses[keyof UpdateAgendaEntryResponses];

export type MoveAgendaEntryData = {
    body: UpdateAgendaEntrySlotRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/entries/{id}/slot';
};

export type MoveAgendaEntryResponses = {
    /**
     * OK
     */
    200: InlineAgendaEntry;
};

export type MoveAgendaEntryResponse = MoveAgendaEntryResponses[keyof MoveAgendaEntryResponses];

export type ExportIcalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agenda/ical';
};

export type ExportIcalResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportIcalResponse = ExportIcalResponses[keyof ExportIcalResponses];

export type SubscribeIcalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agenda/ical/subscribe';
};

export type SubscribeIcalResponses = {
    /**
     * OK
     */
    200: string;
};

export type SubscribeIcalResponse = SubscribeIcalResponses[keyof SubscribeIcalResponses];

export type RemoveRoomData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/rooms/{id}';
};

export type RemoveRoomResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateRoomData = {
    body: UpdateRoomRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/agenda/rooms/{id}';
};

export type UpdateRoomResponses = {
    /**
     * OK
     */
    200: InlineRoom;
};

export type UpdateRoomResponse = UpdateRoomResponses[keyof UpdateRoomResponses];

export type GetAgendaEntriesByDayData = {
    body?: never;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/agenda/{dayId}/entries';
};

export type GetAgendaEntriesByDayResponses = {
    /**
     * OK
     */
    200: Array<InlineAgendaEntry>;
};

export type GetAgendaEntriesByDayResponse = GetAgendaEntriesByDayResponses[keyof GetAgendaEntriesByDayResponses];

export type GetAllRooms1Data = {
    body?: never;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/agenda/{dayId}/rooms';
};

export type GetAllRooms1Responses = {
    /**
     * OK
     */
    200: Array<InlineRoom>;
};

export type GetAllRooms1Response = GetAllRooms1Responses[keyof GetAllRooms1Responses];

export type CreateRoomData = {
    body: CreateRoomRequest;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/agenda/{dayId}/rooms';
};

export type CreateRoomResponses = {
    /**
     * OK
     */
    200: InlineRoom;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type GetAllTimeSlotsData = {
    body?: never;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/agenda/{dayId}/time-slots';
};

export type GetAllTimeSlotsResponses = {
    /**
     * OK
     */
    200: Array<InlineTimeSlot>;
};

export type GetAllTimeSlotsResponse = GetAllTimeSlotsResponses[keyof GetAllTimeSlotsResponses];

export type CreateTimeSlotData = {
    body: CreateTimeSlotRequest;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/agenda/{dayId}/time-slots';
};

export type CreateTimeSlotResponses = {
    /**
     * OK
     */
    200: InlineTimeSlot;
};

export type CreateTimeSlotResponse = CreateTimeSlotResponses[keyof CreateTimeSlotResponses];

export type DeleteTimeSlotData = {
    body?: never;
    path: {
        dayId: string;
        displayOrder: number;
    };
    query?: never;
    url: '/agenda/{dayId}/time-slots/{displayOrder}';
};

export type DeleteTimeSlotResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateTimeSlotData = {
    body: UpdateTimeSlotRequest;
    path: {
        dayId: string;
        displayOrder: number;
    };
    query?: never;
    url: '/agenda/{dayId}/time-slots/{displayOrder}';
};

export type UpdateTimeSlotResponses = {
    /**
     * OK
     */
    200: InlineTimeSlot;
};

export type UpdateTimeSlotResponse = UpdateTimeSlotResponses[keyof UpdateTimeSlotResponses];

export type AuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/allegro/authorize';
};

export type AuthorizeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type Callback1Data = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state: string;
    };
    url: '/allegro/callback';
};

export type Callback1Responses = {
    /**
     * OK
     */
    200: string;
};

export type Callback1Response = Callback1Responses[keyof Callback1Responses];

export type DoImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/allegro/import';
};

export type DoImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ImportFromAllegroData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/allegro/report/ready-to-send';
};

export type ImportFromAllegroResponses = {
    /**
     * OK
     */
    200: string;
};

export type ImportFromAllegroResponse = ImportFromAllegroResponses[keyof ImportFromAllegroResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/allegro/status';
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetTweetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tweets';
};

export type GetTweetsResponses = {
    /**
     * OK
     */
    200: Array<Tweet>;
};

export type GetTweetsResponse = GetTweetsResponses[keyof GetTweetsResponses];

export type AskData = {
    body: AskRequest;
    path?: never;
    query?: never;
    url: '/chat/ask';
};

export type AskResponses = {
    /**
     * OK
     */
    200: SseEmitter;
};

export type AskResponse = AskResponses[keyof AskResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/current-user';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ArrivalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/arrivals';
};

export type ArrivalsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ArrivalsResponse = ArrivalsResponses[keyof ArrivalsResponses];

export type GetMealStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/meal';
};

export type GetMealStatsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMealStatsResponse = GetMealStatsResponses[keyof GetMealStatsResponses];

export type NewsletterStatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/newsletter';
};

export type NewsletterStatResponses = {
    /**
     * OK
     */
    200: NewsletterStat;
};

export type NewsletterStatResponse = NewsletterStatResponses[keyof NewsletterStatResponses];

export type GetRegistrationStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/registration';
};

export type GetRegistrationStatsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRegistrationStatsResponse = GetRegistrationStatsResponses[keyof GetRegistrationStatsResponses];

export type RegistrationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/registrations';
};

export type RegistrationsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RegistrationsResponse = RegistrationsResponses[keyof RegistrationsResponses];

export type SubmissionStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/submissions';
};

export type SubmissionStatsResponses = {
    /**
     * OK
     */
    200: SubmittedStats;
};

export type SubmissionStatsResponse = SubmissionStatsResponses[keyof SubmissionStatsResponses];

export type GetTShirtSizesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/tshirts';
};

export type GetTShirtSizesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetTShirtSizesResponse = GetTShirtSizesResponses[keyof GetTShirtSizesResponses];

export type UsersStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/users';
};

export type UsersStatsResponses = {
    /**
     * OK
     */
    200: UsersStats;
};

export type UsersStatsResponse = UsersStatsResponses[keyof UsersStatsResponses];

export type VotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/votes';
};

export type VotesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type VotesResponse = VotesResponses[keyof VotesResponses];

export type GetVoucherStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/vouchers';
};

export type GetVoucherStatsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVoucherStatsResponse = GetVoucherStatsResponses[keyof GetVoucherStatsResponses];

export type GetAllDaysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/days';
};

export type GetAllDaysResponses = {
    /**
     * OK
     */
    200: Array<InlineDay>;
};

export type GetAllDaysResponse = GetAllDaysResponses[keyof GetAllDaysResponses];

export type SaveDayData = {
    body: Day;
    path?: never;
    query?: never;
    url: '/days';
};

export type SaveDayResponses = {
    /**
     * OK
     */
    200: InlineDay;
};

export type SaveDayResponse = SaveDayResponses[keyof SaveDayResponses];

export type DeleteDayData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/days/{id}';
};

export type DeleteDayResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetDayByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/days/{id}';
};

export type GetDayByIdResponses = {
    /**
     * OK
     */
    200: InlineDay;
};

export type GetDayByIdResponse = GetDayByIdResponses[keyof GetDayByIdResponses];

export type UpdateDayData = {
    body: UpdateDayRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/days/{id}';
};

export type UpdateDayResponses = {
    /**
     * OK
     */
    200: InlineDay;
};

export type UpdateDayResponse = UpdateDayResponses[keyof UpdateDayResponses];

export type GetPublishedFaqEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/faq-entries';
};

export type GetPublishedFaqEntriesResponses = {
    /**
     * OK
     */
    200: Array<FaqEntryDto>;
};

export type GetPublishedFaqEntriesResponse = GetPublishedFaqEntriesResponses[keyof GetPublishedFaqEntriesResponses];

export type CreateFaqEntryData = {
    body: FaqEntryRequest;
    path?: never;
    query?: never;
    url: '/faq-entries';
};

export type CreateFaqEntryResponses = {
    /**
     * OK
     */
    200: FaqEntryDto;
};

export type CreateFaqEntryResponse = CreateFaqEntryResponses[keyof CreateFaqEntryResponses];

export type GetAllFaqEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/faq-entries/all';
};

export type GetAllFaqEntriesResponses = {
    /**
     * OK
     */
    200: Array<FaqEntryDto>;
};

export type GetAllFaqEntriesResponse = GetAllFaqEntriesResponses[keyof GetAllFaqEntriesResponses];

export type RenameCategoryData = {
    body: RenameCategoryRequest;
    path?: never;
    query?: never;
    url: '/faq-entries/category';
};

export type RenameCategoryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: number;
    };
};

export type RenameCategoryResponse = RenameCategoryResponses[keyof RenameCategoryResponses];

export type ImportFromFaqPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/faq-entries/import';
};

export type ImportFromFaqPageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: number;
    };
};

export type ImportFromFaqPageResponse = ImportFromFaqPageResponses[keyof ImportFromFaqPageResponses];

export type ReorderFaqEntriesData = {
    body: ReorderRequest;
    path?: never;
    query?: never;
    url: '/faq-entries/order';
};

export type ReorderFaqEntriesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteFaqEntryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/faq-entries/{id}';
};

export type DeleteFaqEntryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetFaqEntryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/faq-entries/{id}';
};

export type GetFaqEntryResponses = {
    /**
     * OK
     */
    200: FaqEntryDto;
};

export type GetFaqEntryResponse = GetFaqEntryResponses[keyof GetFaqEntryResponses];

export type UpdateFaqEntryData = {
    body: FaqEntryRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/faq-entries/{id}';
};

export type UpdateFaqEntryResponses = {
    /**
     * OK
     */
    200: FaqEntryDto;
};

export type UpdateFaqEntryResponse = UpdateFaqEntryResponses[keyof UpdateFaqEntryResponses];

export type GetLikesData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/likes';
};

export type GetLikesResponses = {
    /**
     * OK
     */
    200: Array<LikeResponse>;
};

export type GetLikesResponse = GetLikesResponses[keyof GetLikesResponses];

export type GetLikesSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/likes/summary';
};

export type GetLikesSummaryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: number;
    };
};

export type GetLikesSummaryResponse = GetLikesSummaryResponses[keyof GetLikesSummaryResponses];

export type DeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/likes/{id}';
};

export type DeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RedirectToTwitterLoginData = {
    body?: never;
    path?: never;
    query: {
        redirect_uri: string;
        state: string;
    };
    url: '/login/twitter';
};

export type RedirectToTwitterLoginResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RedirectToTwitterLoginResponse = RedirectToTwitterLoginResponses[keyof RedirectToTwitterLoginResponses];

export type DoLoginWithTwitterData = {
    body?: never;
    path?: never;
    query: {
        oauth_token: string;
        oauth_verifier: string;
    };
    url: '/login/twitter/callback';
};

export type DoLoginWithTwitterResponses = {
    /**
     * OK
     */
    200: string;
};

export type DoLoginWithTwitterResponse = DoLoginWithTwitterResponses[keyof DoLoginWithTwitterResponses];

export type LoginInProviderData = {
    body?: never;
    path: {
        provider: string;
    };
    query: {
        state: string;
    };
    url: '/login/{provider}';
};

export type LoginInProviderResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type LoginInProviderResponse = LoginInProviderResponses[keyof LoginInProviderResponses];

export type CallbackData = {
    body?: never;
    path: {
        provider: string;
    };
    query: {
        state: string;
        code: string;
    };
    url: '/login/{provider}/callback';
};

export type CallbackResponses = {
    /**
     * OK
     */
    200: string;
};

export type CallbackResponse = CallbackResponses[keyof CallbackResponses];

export type SendMailsData = {
    body: SendMailsRequestWritable;
    path?: never;
    query?: never;
    url: '/mailing';
};

export type SendMailsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mailing/templates';
};

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type GetPagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pages';
};

export type GetPagesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetPagesResponse = GetPagesResponses[keyof GetPagesResponses];

export type DeletePageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/pages/{id}';
};

export type DeletePageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/pages/{id}';
};

export type GetPageResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetPageResponse = GetPageResponses[keyof GetPageResponses];

export type CreatePageData = {
    body: PageContent;
    path: {
        id: string;
    };
    query?: never;
    url: '/pages/{id}';
};

export type CreatePageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type CreatePageResponse = CreatePageResponses[keyof CreatePageResponses];

export type UpdatePageData = {
    body: PageContent;
    path: {
        id: string;
    };
    query?: never;
    url: '/pages/{id}';
};

export type UpdatePageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdatePageResponse = UpdatePageResponses[keyof UpdatePageResponses];

export type GetPublishedPartnersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/partners';
};

export type GetPublishedPartnersResponses = {
    /**
     * OK
     */
    200: Array<PartnerDto>;
};

export type GetPublishedPartnersResponse = GetPublishedPartnersResponses[keyof GetPublishedPartnersResponses];

export type CreatePartnerData = {
    body: PartnerRequest;
    path?: never;
    query?: never;
    url: '/partners';
};

export type CreatePartnerResponses = {
    /**
     * OK
     */
    200: PartnerDto;
};

export type CreatePartnerResponse = CreatePartnerResponses[keyof CreatePartnerResponses];

export type GetAllPartnersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/partners/all';
};

export type GetAllPartnersResponses = {
    /**
     * OK
     */
    200: Array<PartnerDto>;
};

export type GetAllPartnersResponse = GetAllPartnersResponses[keyof GetAllPartnersResponses];

export type DeletePartnerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/partners/{id}';
};

export type DeletePartnerResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPartnerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/partners/{id}';
};

export type GetPartnerResponses = {
    /**
     * OK
     */
    200: PartnerDto;
};

export type GetPartnerResponse = GetPartnerResponses[keyof GetPartnerResponses];

export type UpdatePartnerData = {
    body: PartnerRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/partners/{id}';
};

export type UpdatePartnerResponses = {
    /**
     * OK
     */
    200: PartnerDto;
};

export type UpdatePartnerResponse = UpdatePartnerResponses[keyof UpdatePartnerResponses];

export type GetAllPresentationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/presentations';
};

export type GetAllPresentationsResponses = {
    /**
     * OK
     */
    200: Array<FullPresentation>;
};

export type GetAllPresentationsResponse = GetAllPresentationsResponses[keyof GetAllPresentationsResponses];

export type AcceptData = {
    body?: never;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/accept';
};

export type AcceptResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AcceptResponse = AcceptResponses[keyof AcceptResponses];

export type GetCospeakersData = {
    body?: never;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/cospeakers';
};

export type GetCospeakersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetCospeakersResponse = GetCospeakersResponses[keyof GetCospeakersResponses];

export type AddCospeakerData = {
    body?: never;
    path: {
        presentationId: string;
        email: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/cospeakers/{email}';
};

export type AddCospeakerResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AddCospeakerResponse = AddCospeakerResponses[keyof AddCospeakerResponses];

export type RemoveCospeakerData = {
    body?: never;
    path: {
        presentationId: string;
        id: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/cospeakers/{id}';
};

export type RemoveCospeakerResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RemoveCospeakerResponse = RemoveCospeakerResponses[keyof RemoveCospeakerResponses];

export type CountByPresentationData = {
    body?: never;
    path: {
        presentationId: PresentationWritable;
    };
    query?: never;
    url: '/presentations/{presentationId}/likes';
};

export type CountByPresentationResponses = {
    /**
     * OK
     */
    200: number;
};

export type CountByPresentationResponse = CountByPresentationResponses[keyof CountByPresentationResponses];

export type CreateVoteData = {
    body: LikeWritable;
    path: {
        presentationId: PresentationWritable;
    };
    query?: never;
    url: '/presentations/{presentationId}/likes';
};

export type CreateVoteResponses = {
    /**
     * OK
     */
    200: string;
};

export type CreateVoteResponse = CreateVoteResponses[keyof CreateVoteResponses];

export type SetPreSelectionData = {
    body: PreSelectionRequest;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/pre-selection';
};

export type SetPreSelectionResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type SetPreSelectionResponse = SetPreSelectionResponses[keyof SetPreSelectionResponses];

export type Rates1Data = {
    body?: never;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/ratings';
};

export type Rates1Responses = {
    /**
     * OK
     */
    200: ViewPresentationRate;
};

export type Rates1Response = Rates1Responses[keyof Rates1Responses];

export type AddRatingData = {
    body: RateRequest;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/ratings';
};

export type AddRatingResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AddRatingResponse = AddRatingResponses[keyof AddRatingResponses];

export type UpdateRatingData = {
    body: RateWritable;
    path: {
        presentationId: string;
        ratingId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/ratings/{ratingId}';
};

export type UpdateRatingResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateRatingResponse = UpdateRatingResponses[keyof UpdateRatingResponses];

export type RejectData = {
    body?: never;
    path: {
        presentationId: string;
    };
    query?: never;
    url: '/presentations/{presentationId}/reject';
};

export type RejectResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RejectResponse = RejectResponses[keyof RejectResponses];

export type AgendaData = {
    body?: never;
    path: {
        dayId: string;
    };
    query?: never;
    url: '/published/agenda/{dayId}';
};

export type AgendaResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AgendaResponse = AgendaResponses[keyof AgendaResponses];

export type NewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/published/news';
};

export type NewsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type NewsResponse = NewsResponses[keyof NewsResponses];

export type PageData = {
    body?: never;
    path: {
        page: string;
    };
    query?: never;
    url: '/published/pages/{page}';
};

export type PageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PageResponse = PageResponses[keyof PageResponses];

export type AcceptedPresentationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/published/presentations/accepted';
};

export type AcceptedPresentationsResponses = {
    /**
     * OK
     */
    200: Array<InlinePresentationWithSpeakers>;
};

export type AcceptedPresentationsResponse = AcceptedPresentationsResponses[keyof AcceptedPresentationsResponses];

export type AdminsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/published/users/search/admins';
};

export type AdminsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminsResponse = AdminsResponses[keyof AdminsResponses];

export type SpeakersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/published/users/search/speakers';
};

export type SpeakersResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type SpeakersResponse = SpeakersResponses[keyof SpeakersResponses];

export type SpeakerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/published/users/{id}/public';
};

export type SpeakerResponses = {
    /**
     * OK
     */
    200: PublicSpeaker;
};

export type SpeakerResponse = SpeakerResponses[keyof SpeakerResponses];

export type AcceptedWorkshopsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/published/workshops/accepted';
};

export type AcceptedWorkshopsResponses = {
    /**
     * OK
     */
    200: Array<InlinePresentationWithSpeakers>;
};

export type AcceptedWorkshopsResponse = AcceptedWorkshopsResponses[keyof AcceptedWorkshopsResponses];

export type RatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ratings';
};

export type RatesResponses = {
    /**
     * OK
     */
    200: Array<ViewPresentationRate>;
};

export type RatesResponse = RatesResponses[keyof RatesResponses];

export type StorePartnerLogoData = {
    /**
     * File to upload
     */
    body?: {
        file?: Blob | File;
    };
    path: {
        /**
         * ID of the partner
         */
        id: string;
    };
    query?: never;
    url: '/resources/partners/{id}';
};

export type StorePartnerLogoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StoreUserProfilePictureData = {
    /**
     * File to upload
     */
    body?: {
        file?: Blob | File;
    };
    path: {
        /**
         * ID of the user
         */
        userId: string;
    };
    query?: never;
    url: '/resources/{userId}';
};

export type StoreUserProfilePictureResponses = {
    /**
     * OK
     */
    200: string;
};

export type StoreUserProfilePictureResponse = StoreUserProfilePictureResponses[keyof StoreUserProfilePictureResponses];

export type GetAllRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type GetAllRoomsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetAllRoomsResponse = GetAllRoomsResponses[keyof GetAllRoomsResponses];

export type SaveRoomData = {
    body: Room;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type SaveRoomResponses = {
    /**
     * OK
     */
    200: Room;
};

export type SaveRoomResponse = SaveRoomResponses[keyof SaveRoomResponses];

export type DeleteRoomData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type DeleteRoomResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRoomByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type GetRoomByIdResponses = {
    /**
     * OK
     */
    200: Room;
};

export type GetRoomByIdResponse = GetRoomByIdResponses[keyof GetRoomByIdResponses];

export type GetAllTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type GetAllTagsResponses = {
    /**
     * OK
     */
    200: Array<Tag>;
};

export type GetAllTagsResponse = GetAllTagsResponses[keyof GetAllTagsResponses];

export type SaveTagsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/tags';
};

export type SaveTagsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type SaveTagsResponse = SaveTagsResponses[keyof SaveTagsResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tokens/refresh-token';
};

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: string;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<FullUser>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type Save1Data = {
    body: User;
    path?: never;
    query?: never;
    url: '/users';
};

export type Save1Responses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type Save1Response = Save1Responses[keyof Save1Responses];

export type CreateManualData = {
    body: User;
    path?: never;
    query?: never;
    url: '/users/manual';
};

export type CreateManualResponses = {
    /**
     * OK
     */
    200: FullUser;
};

export type CreateManualResponse = CreateManualResponses[keyof CreateManualResponses];

export type GetAdminsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/search/admins';
};

export type GetAdminsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetAdminsResponse = GetAdminsResponses[keyof GetAdminsResponses];

export type GetSpeakersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/search/speakers';
};

export type GetSpeakersResponses = {
    /**
     * OK
     */
    200: Array<PublicSpeaker>;
};

export type GetSpeakersResponse = GetSpeakersResponses[keyof GetSpeakersResponses];

export type GetVolunteersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/search/volunteers';
};

export type GetVolunteersResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVolunteersResponse = GetVolunteersResponses[keyof GetVolunteersResponses];

export type GetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type GetUserPresentationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/presentations';
};

export type GetUserPresentationsResponses = {
    /**
     * OK
     */
    200: Array<InlinePresentation>;
};

export type GetUserPresentationsResponse = GetUserPresentationsResponses[keyof GetUserPresentationsResponses];

export type GetPresentationData = {
    body?: never;
    path: {
        id: string;
        presentationId: string;
    };
    query?: never;
    url: '/users/{id}/presentations/{presentationId}';
};

export type GetPresentationResponses = {
    /**
     * OK
     */
    200: InlinePresentation;
};

export type GetPresentationResponse = GetPresentationResponses[keyof GetPresentationResponses];

export type GetPublicByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/public';
};

export type GetPublicByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPublicByIdResponse = GetPublicByIdResponses[keyof GetPublicByIdResponses];

export type GetUserWorkshopsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}/workshops';
};

export type GetUserWorkshopsResponses = {
    /**
     * OK
     */
    200: Array<InlineWorkshop>;
};

export type GetUserWorkshopsResponse = GetUserWorkshopsResponses[keyof GetUserWorkshopsResponses];

export type GetWorkshopData = {
    body?: never;
    path: {
        id: string;
        workshopId: string;
    };
    query?: never;
    url: '/users/{id}/workshops/{workshopId}';
};

export type GetWorkshopResponses = {
    /**
     * OK
     */
    200: InlineWorkshop;
};

export type GetWorkshopResponse = GetWorkshopResponses[keyof GetWorkshopResponses];

export type MarkAsAdminData = {
    body?: never;
    path: {
        userId: string;
        isAdmin: boolean;
    };
    query?: never;
    url: '/users/{userId}/admin/{isAdmin}';
};

export type MarkAsAdminResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type MarkAsAdminResponse = MarkAsAdminResponses[keyof MarkAsAdminResponses];

export type AssignParticipationDataData = {
    body: ParticipationData;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/participationData';
};

export type AssignParticipationDataResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AssignParticipationDataResponse = AssignParticipationDataResponses[keyof AssignParticipationDataResponses];

export type AddPresentationToUserData = {
    body: PresentationRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/presentations';
};

export type AddPresentationToUserResponses = {
    /**
     * OK
     */
    200: InlinePresentation;
};

export type AddPresentationToUserResponse = AddPresentationToUserResponses[keyof AddPresentationToUserResponses];

export type DeletePresentationData = {
    body?: never;
    path: {
        userId: string;
        presentationId: string;
    };
    query?: never;
    url: '/users/{userId}/presentations/{presentationId}';
};

export type DeletePresentationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdatePresentationData = {
    body: PresentationRequest;
    path: {
        userId: string;
        presentationId: string;
    };
    query?: never;
    url: '/users/{userId}/presentations/{presentationId}';
};

export type UpdatePresentationResponses = {
    /**
     * OK
     */
    200: InlinePresentation;
};

export type UpdatePresentationResponse = UpdatePresentationResponses[keyof UpdatePresentationResponses];

export type MarkAsVolunteerData = {
    body?: never;
    path: {
        userId: string;
        isVolunteer: boolean;
    };
    query?: never;
    url: '/users/{userId}/volunteer/{isVolunteer}';
};

export type MarkAsVolunteerResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type MarkAsVolunteerResponse = MarkAsVolunteerResponses[keyof MarkAsVolunteerResponses];

export type AddWorkshopToUserData = {
    body: WorkshopRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/workshops';
};

export type AddWorkshopToUserResponses = {
    /**
     * OK
     */
    200: InlineWorkshop;
};

export type AddWorkshopToUserResponse = AddWorkshopToUserResponses[keyof AddWorkshopToUserResponses];

export type DeleteWorkshopData = {
    body?: never;
    path: {
        userId: string;
        workshopId: string;
    };
    query?: never;
    url: '/users/{userId}/workshops/{workshopId}';
};

export type DeleteWorkshopResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateWorkshopData = {
    body: WorkshopRequest;
    path: {
        userId: string;
        workshopId: string;
    };
    query?: never;
    url: '/users/{userId}/workshops/{workshopId}';
};

export type UpdateWorkshopResponses = {
    /**
     * OK
     */
    200: InlineWorkshop;
};

export type UpdateWorkshopResponse = UpdateWorkshopResponses[keyof UpdateWorkshopResponses];

export type SaveData = {
    body: VoteRequest;
    path?: never;
    query?: never;
    url: '/votes';
};

export type SaveResponses = {
    /**
     * OK
     */
    200: InlineVote;
};

export type SaveResponse = SaveResponses[keyof SaveResponses];

export type ResultsData = {
    body?: never;
    path?: never;
    query?: {
        tokens?: Array<string>;
    };
    url: '/votes/results';
};

export type ResultsResponses = {
    /**
     * OK
     */
    200: Array<VoteResult>;
};

export type ResultsResponse = ResultsResponses[keyof ResultsResponses];

export type StartData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/votes/start/{token}';
};

export type StartResponses = {
    /**
     * OK
     */
    200: Array<InlineVote>;
};

export type StartResponse = StartResponses[keyof StartResponses];

export type StatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/votes/statistics';
};

export type StatisticsResponses = {
    /**
     * OK
     */
    200: Array<PresentationStats>;
};

export type StatisticsResponse = StatisticsResponses[keyof StatisticsResponses];

export type FindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vouchers';
};

export type FindAllResponses = {
    /**
     * OK
     */
    200: Array<Voucher>;
};

export type FindAllResponse = FindAllResponses[keyof FindAllResponses];

export type CreateVoucherData = {
    body: GenerateVouchersRequest;
    path?: never;
    query?: never;
    url: '/vouchers';
};

export type CreateVoucherResponses = {
    /**
     * OK
     */
    200: Array<Voucher>;
};

export type CreateVoucherResponse = CreateVoucherResponses[keyof CreateVoucherResponses];

export type SendVouchersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vouchers/send';
};

export type SendVouchersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CanUseVoucherData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/vouchers/{id}/check';
};

export type CanUseVoucherResponses = {
    /**
     * OK
     */
    200: RegistrationError;
};

export type CanUseVoucherResponse = CanUseVoucherResponses[keyof CanUseVoucherResponses];

export type ResendVoucherData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/vouchers/{id}/re-send';
};

export type ResendVoucherResponses = {
    /**
     * OK
     */
    200: unknown;
};
