
name: Deploy next
on:
  push:
    branches: [ next ]

jobs:

  deploy-frontend:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: confitura-vue

    steps:
      - uses: actions/checkout@v3
      - run: nvm install 12
      - run: nvm use 12
      - run: npm ci
      - run: npm run build
      - run: rm -rf /var/www/github-deployed/next.confitura.pl && cp -r dist /var/www/github-deployed/next.confitura.pl

  deploy-console:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: confitura-page

    steps:
      - uses: actions/checkout@v3
      - run: nvm install 12
      - run: nvm use 12
      - run: npm ci
      - run: npm run build
      - run: rm -rf /var/www/github-deployed/next-console.confitura.pl && cp -r dist /var/www/github-deployed/next-console.confitura.pl
