
name: Deploy prod

on:
  push:
    branches: [ master ]

jobs:
  deploy-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: jelatyna-backend

    steps:
      - uses: actions/checkout@v3
      - name: print version
        run: ./mvnw -version
      - name: Build with Maven
        run: ./mvnw -B package -DskipTests
      - run: cp target/jelatyna-*.jar /home/jelatyna/github/jelatyna.jar
      - working-directory: .
        run: cp .github/config/application.yml /home/jelatyna/github/application.yml
      - run: sudo systemctl restart jelatyna