
name: Deploy prod

on:
  push:
    branches: [ master ]

jobs:
  deploy-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: jelatyna-backend

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: ./mvnw -B package -DskipTests
      - run: cp target/jelatyna-*.jar /home/jelatyna/github/jelatyna.jar
      - working-directory: .
        run: cp .github/config/application.yml /home/jelatyna/github/application.yml
      - run: sudo systemctl restart jelatyna

  deploy-frontend:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: confitura-vue

    steps:
      - uses: actions/checkout@v3
      - run: nvm install 12
      - run: nvm use 12
      - run: npm ci
      - run: npm run build
      - run: rm -rf /var/www/github-deployed/2022.confitura.pl && cp -r dist /var/www/github-deployed/2022.confitura.pl

  deploy-console:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: confitura-page

    steps:
      - uses: actions/checkout@v3
      - run: nvm install 12
      - run: nvm use 12
      - run: npm ci
      - run: npm run build
      - run: rm -rf /var/www/github-deployed/2022-console.confitura.pl && cp -r dist /var/www/github-deployed/2022-console.confitura.pl
